-- noinspection SqlNoDataSourceInspectionForFile

INSERT INTO STUDENTS(ID, NAME) VALUES(1, 'Jasiu');
INSERT INTO STUDENTS(ID, NAME) VALUES(2, 'Malgosia');

INSERT INTO STUDENT_NOTES(ID, STUDENT_ID, NOTE) VALUES(1, 1, 1);
INSERT INTO STUDENT_NOTES(ID, STUDENT_ID, NOTE) VALUES(2, 1, 2);
INSERT INTO STUDENT_NOTES(ID, STUDENT_ID, NOTE) VALUES(3, 1, 1);

INSERT INTO STUDENT_NOTES(ID, STUDENT_ID, NOTE) VALUES(4, 2, 5);
INSERT INTO STUDENT_NOTES(ID, STUDENT_ID, NOTE) VALUES(5, 2, 6);
INSERT INTO STUDENT_NOTES(ID, STUDENT_ID, NOTE) VALUES(6, 2, 6);

